### ISSUE TITLE
Fix docker push to Azure container registry

### ISSUE THREAD

**Issue by matt-primrose** [open-amt-cloud-toolkit/open-amt-cloud-toolkit#234]
- [x] Fix Docker image push to Azure with version tag to issue
  - [x] Update MPS open-amt-cloud-toolkit/mps#1064
  - [x] Update RPS open-amt-cloud-toolkit/rps#1204
  - [x] Update RPC-Go open-amt-cloud-toolkit/rpc-go#221
  - [x] Update MPS Router open-amt-cloud-toolkit/mps-router#98
  - [x] Update Sample Web UI open-amt-cloud-toolkit/sample-web-ui#1364
- [x] Work with Ernesto
