### ISSUE TITLE
Deploy Security Report Action across all repositories

### ISSUE THREAD

**Issue by mechris1** [open-amt-cloud-toolkit/open-amt-cloud-toolkit#244]
Currently the Security Report Action is only configured for RPS.  Need to add it for the other repos:

- [x]  RPS [#1295](https://github.com/open-amt-cloud-toolkit/rps/pull/1295)
- [x]  MPS [#1157](https://github.com/open-amt-cloud-toolkit/mps/pull/1157)
- [x]  WSMAN-Messages [#610](https://github.com/open-amt-cloud-toolkit/wsman-messages/pull/610)
- [x]  Sample-Web-UI [#1475](https://github.com/open-amt-cloud-toolkit/sample-web-ui/pull/1475)
- [x]  UI-Toolkit [#790](https://github.com/open-amt-cloud-toolkit/ui-toolkit/pull/790)
- [x]  UI-Toolkit-angular [#905](https://github.com/open-amt-cloud-toolkit/ui-toolkit-angular/pull/905)
- [x]  UI-Toolkit-react [#903](https://github.com/open-amt-cloud-toolkit/ui-toolkit-react/pull/903)
- [x]  RPC-Go [#283](https://github.com/open-amt-cloud-toolkit/rpc-go/pull/283)
- [x]  Go-Wsman-Messages [#123](https://github.com/open-amt-cloud-toolkit/go-wsman-messages/pull/123)
- [ ]  Enterprise Assistant (Stretch, may not be supported)
- [x] Triggered to run when there is a release...

**Comment by Craig-Spencer-12** [comment]
Draft PR Created

- [ ] - [ ]  MPS
- [ ]  WSMAN-Messages
- [ ]  Sample-Web-UI
- [ ]  UI-Toolkit
- [ ]  UI-Toolkit-angular
- [ ]  UI-Toolkit-react
- [ ]  RPC-Go
- [ ]  Go-Wsman-Messages
- [ ]  Enterprise Assistant (Stretch, may not be supported)
- [ ]  Triggered to run when there is a release...
